# Generated by Django 2.2.3 on 2019-07-28 17:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0002_emailpush'),
    ]

    operations = [
        migrations.CreateModel(
            name='LinePush',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_id', models.CharField(max_length=100, unique=True, verbose_name='ユーザーID')),
            ],
        ),
    ]
